version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
#    volumes:
#      - mongodb:/data/db
#      - mongodb_config:/data/configdb

  neo4j:
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: none # development only
#    volumes:
#      - neo4j:/data


#volumes:
#  mongodb:
#  mongodb_config:
#  neo4j:
