version: "3.8"

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    #    volumes:
    #      - mongodb:/data/db
    #      - mongodb_config:/data/configdb
    container_name: lbd_mongo
    profiles:
      - dbs
      - all
    volumes:
      - ./seeds/:/seeds/

  neo4j:
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: none # development only
    #    volumes:
    #      - neo4j:/data
    container_name: lbd_neo4j
    profiles:
      - dbs
      - all
  postgres:
    image: postgres:14.4
    restart: always
    container_name: lbd_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - 5432:5432
    volumes:
      - ./seeds/populate_postgres.sql:/docker-entrypoint-initdb.d/populate_postgres.sql
      - ./seeds/:/seeds/

volumes:
  build:
#  mongodb:
#  mongodb_config:
#  neo4j:
