version: '3.8'

services:
  spring-common:
    build:
      context: .
      dockerfile: Dockerfile-dev
    working_dir: /app
    volumes:
      - ./src:/app/src
      - build:/app/build
    profiles:
      - spring-common

  bootrun:
    extends:
      service: spring-common
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - 8080:8080
      - 35729:35729
    container_name: lbd_spring
    profiles:
      - dev
      - all
    command: ./gradlew bootRun

  build:
    extends:
      service: spring-common
    container_name: lbd_dev
    profiles:
      - dev
      - all
    command: ./gradlew build --continuous -x test

volumes:
  build:
