version: '3.8'

services:
  spring:
    image: openjdk:17-jdk-alpine
    working_dir: /app
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - ./:/app
    command: ./gradlew bootRun

  mongo:
    image: mongo
    ports:
      - 27017:27017
#    volumes:
#      - mongodb:/data/db
#      - mongodb_config:/data/configdb

#volumes:
#  mongodb:
#  mongodb_config:
